### ISSUE TITLE
Can't set sampler_index with set shortcode due to it passing it as a float

### ISSUE THREAD

**Issue by f8upd8** [ThereforeGames/unprompted#10]
Template text:

[set sampler_index]1[/set]

Exception:

```
Traceback (most recent call last):
  File "F:\sd\automatic-webui-win11\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "F:\sd\automatic-webui-win11\webui.py", line 55, in f
    res = func(*args, **kwargs)
  File "F:\sd\automatic-webui-win11\modules\txt2img.py", line 48, in txt2img
    processed = process_images(p)
  File "F:\sd\automatic-webui-win11\modules\processing.py", line 423, in process_images
    res = process_images_inner(p)
  File "F:\sd\automatic-webui-win11\modules\processing.py", line 519, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "F:\sd\automatic-webui-win11\modules\processing.py", line 648, in sample
    self.sampler = sd_samplers.create_sampler_with_index(sd_samplers.samplers, self.sampler_index, self.sd_model)
  File "F:\sd\automatic-webui-win11\modules\sd_samplers.py", line 51, in create_sampler_with_index
    config = list_of_configs[index]
TypeError: list indices must be integers or slices, not float
```

**Comment by f8upd8** [comment]
Same behavior with width and height

**Comment by f8upd8** [comment]
I guess kind of a workaround would be enforce int in case the string has a .0 floating point? That'd eliminate the issue

**Comment by ThereforeGames** [comment]
Hi @MalOMaw,

I have updated the datatype casting logic for `[set]` in v0.5.1 - feel free to give it a try and let me know if you run into any other issues. Thank you!
