### ISSUE TITLE
'Unprompted' object has no attribute 'p_copy'

### ISSUE THREAD

**Issue by umishima** [ThereforeGames/unprompted#119]
Great idea and extension, but still impossible to use with any version, bug after bug. The most current is the latest version:

Error running postprocess: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/_unprompted/scripts/unprompted.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/_unprompted/lib_unprompted/shortcodes.py", line 117, in render
    return str(self.handler(self.token.keyword, self.pargs, self.kwargs, context))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/_unprompted/lib_unprompted/shared.py", line 61, in handler
    return(self.shortcode_objects[f"{keyword}"].run_atomic(pargs, kwargs, context))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/_unprompted/shortcodes/stable_diffusion/zoom_enhance.py", line 70, in run_atomic
    if (hasattr(self.Unprompted.p_copy,"image_mask")):
AttributeError: 'Unprompted' object has no attribute 'p_copy'

Any solution how to fix it? Thanks in advance

**Comment by ThereforeGames** [comment]
Hi, I believe this has been fixed - the `p_copy` object was expecting you to have opted into `Unprompted.Config.beta_features`, but this is no longer required.

**Comment by umishima** [comment]
Thanks for fast fix, p_copy is gone, but new one appear(

Error running postprocess: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/_unprompted/scripts/unprompted.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/_unprompted/lib_unprompted/shortcodes.py", line 117, in render
    return str(self.handler(self.token.keyword, self.pargs, self.kwargs, context))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/_unprompted/lib_unprompted/shared.py", line 61, in handler
    return(self.shortcode_objects[f"{keyword}"].run_atomic(pargs, kwargs, context))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/_unprompted/shortcodes/stable_diffusion/zoom_enhance.py", line 295, in run_atomic
    sub_img_big = self.Unprompted.color_match(starting_image_face_big,sub_img_big,color_correct_method,color_correct_strength)
AttributeError: 'Unprompted' object has no attribute 'color_match'
