### ISSUE TITLE
Issues with [array] shortcode and randomization

### ISSUE THREAD

**Issue by eanism** [ThereforeGames/unprompted#123]
Trying to find a working approach to randomizing elements in an array, but so far have not had any luck. The _shuffle flag seems to generate an error (unless I'm misusing it), and array doesn't seem to be able to unpack nested shortcodes (thought I'd be clever and set a variable to a random int and call it, but no dice)
Test 1:
[array test]
[array test _append="a|b|c|d|e"]
[array test _shuffle]
[get test]
stderr:
Error running process: C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py.60it/s]
Traceback (most recent call last):
  File "C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted\lib_unprompted\shortcodes.py", line 117, in render
    return str(self.handler(self.token.keyword, self.pargs, self.kwargs, context))
  File "C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted\lib_unprompted\shared.py", line 61, in handler
    return(self.shortcode_objects[f"{keyword}"].run_atomic(pargs, kwargs, context))
  File "C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted/shortcodes\basic\array.py", line 32, in run_atomic
    random.shuffle(self.Unprompted.shortcode_user_vars[parg])
KeyError: '_shuffle'

Test 2:
[array test]
[array test _append="a|b|c|d|e"]
[set idx]2[/set]
[array test {get idx}]
sterr:
Traceback (most recent call last):
  File "C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted\lib_unprompted\shortcodes.py", line 117, in render
    return str(self.handler(self.token.keyword, self.pargs, self.kwargs, context))
  File "C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted\lib_unprompted\shared.py", line 61, in handler
    return(self.shortcode_objects[f"{keyword}"].run_atomic(pargs, kwargs, context))
  File "C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted/shortcodes\basic\array.py", line 20, in run_atomic
    result_list.append(str(self.Unprompted.shortcode_user_vars[pargs[0]][int(self.Unprompted.parse_advanced(parg,context))]))
  File "C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted\lib_unprompted\shared.py", line 117, in parse_advanced
    string = self.parse_alt_tags(string,context)
  File "C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted\lib_unprompted\shared.py", line 158, in parse_alt_tags
    return(parser.parse(string,context))
  File "C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted\lib_unprompted\shortcodes.py", line 178, in parse
    for token in lexer.tokenize():
  File "C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted\lib_unprompted\shortcodes.py", line 267, in tokenize
    self.read_tag()
  File "C:\Users\eanis\github\stable-diffusion-webui\extensions\unprompted\lib_unprompted\shortcodes.py", line 289, in read_tag
    raise ShortcodeSyntaxError(msg)
lib_unprompted.shortcodes.ShortcodeSyntaxError: Unclosed shortcode tag. The tag was opened in line 1.

Love this plugin, has totally opened up all sorts of great workflow options, thank you for your great work!

**Comment by ThereforeGames** [comment]
Hi @eanism,

Thank you for reaching out!

I have resolved the issue with array `_shuffle` in Unprompted v8.2.0. Give it a try - you can use your code from Test 1 or even simplify it further:

```
[array test _append="a|b|c|d|e" _shuffle]
[get test]
```

**Comment by eanism** [comment]
Confirmed working. Thank you!
