### ISSUE TITLE
Zoomenhance error in 9.1.0

### ISSUE THREAD

**Issue by freke70** [ThereforeGames/unprompted#138]
New error in version 9.1?

`(ERROR) [../../shortcodes/stable_diffusion/zoom_enhance.py] Traceback (most recent call last):
  File "/home/me/automatic/extensions/unprompted/shortcodes/stable_diffusion/zoom_enhance.py", line 370, in run_atomic
    fixed_image = self.Unprompted.shortcode_objects["img2img"].run_atomic(set_pargs,None,None)
  File "/home/me/automatic/extensions/unprompted/shortcodes/stable_diffusion/img2img.py", line 91, in run_atomic
    if len(img2img_images) < 1:
UnboundLocalError: local variable 'img2img_images' referenced before assignment
`

Let me know if I can provide more info.

**Comment by freke70** [comment]
Just noticed, it does still work in img2img.
But I mainly used it in text2img.
That way, you don't have to first inpaint the face to see if the end-result is worth developing.

**Comment by Helldiver1080** [comment]
Can confirm, getting this error as of today as well
