### ISSUE TITLE
Controlnet presets not working

### ISSUE THREAD

**Issue by HeavyTony2** [ThereforeGames/unprompted#147]
```
Error running process: C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1017, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 689, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 703, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None
```

**Comment by ThereforeGames** [comment]
Hi @HeavyTony2,

Are you receiving the same error for all presets? There are one or two, like `dev.txt`, that may require you to download additional preprocessors/models. You can open up the files at `unprompted/common/presets/controlnet` to see which ControlNet dependencies are needed.
