### ISSUE TITLE
Can you please replace the natural language processing library

### ISSUE THREAD

**Issue by LGlassySky** [ThereforeGames/unprompted#156]
For natural language processing, the PATTERN library only supports Python 3.6. Can we switch to the spaCy library to support the latest Python?

**Comment by ThereforeGames** [comment]
Hi @LGlassySky,

I am able to run NLP features such as `[autocorrect]` that rely on the Pattern library in Python v3.10:

![image](https://github.com/ThereforeGames/unprompted/assets/95403634/9ae2f7ac-2e0f-403f-8a8e-1562de806f9d)

Is there a particular shortcode that's giving you trouble?

**Comment by LGlassySky** [comment]
> Hi @LGlassySky,
> 
> I am able to run NLP features such as that rely on the Pattern library in Python v3.10:`[autocorrect]`
> 
> ![image](https://user-images.githubusercontent.com/95403634/249629859-9ae2f7ac-2e0f-403f-8a8e-1562de806f9d.png)
> 
> Is there a particular shortcode that's giving you trouble?

Hi @ThereforeGames ,

Here is my running environment:
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.3.2

The following error occurs every time I start the webui,
Installing requirements for Unprompted - natural language processing: pattern@git+https://github.com/NicolasBizzozzero/pattern
Couldn't install requirements for Unprompted - natural language processing: pattern@git+https://github.com/NicolasBizzozzero/pattern.
Command: "D:\sd-webui-aki-v4\py310\python.exe" -m pip install pattern@git+https://github.com/NicolasBizzozzero/pattern --prefer-binary --index-url https://mirror.baidu.com/pypi/simple
Error code: 1
stdout: Looking in indexes: https://mirror.baidu.com/pypi/simple, https://mirrors.aliyun.com/pypi/simple
Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html
Collecting pattern@ git+https://github.com/NicolasBizzozzero/pattern
  Cloning https://github.com/NicolasBizzozzero/pattern to c:\users\glassysky\appdata\local\temp\pip-install-xkbl3e6z\pattern_f5c1bf01315546c88915a8c12e953754
  Resolved https://github.com/NicolasBizzozzero/pattern to commit 66ab34453a3443c06a4ebda092c8d1947c83b17a
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/NicolasBizzozzero/pattern 'C:\Users\Glassysky\AppData\Local\Temp\pip-install-xkbl3e6z\pattern_f5c1bf01315546c88915a8c12e953754'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Glassysky\AppData\Local\Temp\pip-install-xkbl3e6z\pattern_f5c1bf01315546c88915a8c12e953754\setup.py", line 12, in <module>
          from pattern import __version__
      ImportError: cannot import name '__version__' from 'pattern' (D:\sd-webui-aki-v4\py310\lib\site-packages\pattern\__init__.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(ERROR) Failed to install pattern@git+https://github.com/NicolasBizzozzero/pattern dependency for Unprompted - natural language processing functions may not work
Installing requirements for Unprompted - [img2pez]: sentence-transformers
Installing requirements for Unprompted - [pix2pix_zero]: salesforce-lavis
Installing requirements for Unprompted - [zoom_enhance]: color-matcher
![image](https://github.com/ThereforeGames/unprompted/assets/36590171/18c09f8b-6432-4d9b-94a2-d7d5b28cc538)
![image](https://github.com/ThereforeGames/unprompted/assets/36590171/1382a4e7-f969-4fb5-b067-0a4215001a08)
