### ISSUE TITLE
KeyError: 'prompt'

### ISSUE THREAD

**Issue by Lemniscatas** [ThereforeGames/unprompted#175]
Hello! After the update, this error appears. How to deal with it?

```
Error running process: C:\Users\user\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py
Traceback (most recent call last):
  File "C:\Users\user\stable-diffusion-webui\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "C:\Users\user\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 633, in process
    Unprompted.populate_stable_diffusion_vars(p)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Unprompted' object has no attribute 'populate_stable_diffusion_vars'

(WARNING) [scripts\unprompted.py] Engaging new process_batch() implementation - if it gives you any trouble, please set batch_method to 'legacy' in your config. This message will be removed in a future update.
Error running process_batch: C:\Users\user\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py
Traceback (most recent call last):
  File "C:\Users\user\stable-diffusion-webui\modules\scripts.py", line 469, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "C:\Users\user\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 665, in process_batch
    prompt_result = Unprompted.shortcode_user_vars["prompt"]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'prompt'
```

**Comment by Lemniscatas** [comment]
I backed up and renamed the plugin with _ at the beginning, and it seems to be ok now

**Comment by ThereforeGames** [comment]
Hi @Lemniscatas,

Thank you for reaching out. Judging from the error message, I think simply restarting the WebUI would have fixed the issue. But it's usually a good idea to rename the folder to `_unprompted` anyway, as it plays better with other extensions. :)
