### ISSUE TITLE
Error with wildcard char

### ISSUE THREAD

**Issue by aniketgore** [ThereforeGames/unprompted#23]
Getting an error when using [file b/places/*]. Below is the error

Error running process: /home/aniket/stable-diffusion-webui/extensions/unprompted/scripts/unprompted.py
Traceback (most recent call last):
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 117, in render
    return str(self.handler(self.token.keyword, self.pargs, self.kwargs, context))
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shared.py", line 50, in handler
    return(self.shortcode_objects[f"{keyword}"].run_atomic(pargs, kwargs, context))
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/shortcodes/basic/file.py", line 18, in run_atomic
    file = random.choice(files)
  File "/usr/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 117, in render
    return str(self.handler(self.token.keyword, self.pargs, self.kwargs, context))
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shared.py", line 50, in handler
    return(self.shortcode_objects[f"{keyword}"].run_atomic(pargs, kwargs, context))
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/shortcodes/basic/file.py", line 25, in run_atomic
    return(self.Unprompted.strip_str(self.Unprompted.shortcode_parser.parse(file_contents,path),self.Unprompted.Config.syntax.n_temp))
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 219, in parse
    return stack.pop().render(context)
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 58, in render
    return ''.join(child.render(context) for child in self.children)
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 58, in <genexpr>
    return ''.join(child.render(context) for child in self.children)
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 121, in render
    raise ShortcodeRenderingError(msg) from ex
lib.shortcodes.ShortcodeRenderingError: An exception was raised while rendering the 'file' shortcode in line 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 117, in render
    return str(self.handler(self.token.keyword, self.pargs, self.kwargs, context))
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shared.py", line 50, in handler
    return(self.shortcode_objects[f"{keyword}"].run_atomic(pargs, kwargs, context))
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/shortcodes/basic/file.py", line 25, in run_atomic
    return(self.Unprompted.strip_str(self.Unprompted.shortcode_parser.parse(file_contents,path),self.Unprompted.Config.syntax.n_temp))
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 219, in parse
    return stack.pop().render(context)
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 58, in render
    return ''.join(child.render(context) for child in self.children)
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 58, in <genexpr>
    return ''.join(child.render(context) for child in self.children)
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 121, in render
    raise ShortcodeRenderingError(msg) from ex
lib.shortcodes.ShortcodeRenderingError: An exception was raised while rendering the 'file' shortcode in line 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aniket/stable-diffusion-webui/modules/scripts.py", line 327, in process
    script.process(p, *script_args)
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/scripts/unprompted.py", line 58, in process
    Unprompted.shortcode_user_vars["prompt"] = Unprompted.process_string(original_prompt)
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shared.py", line 71, in process_string
    string = self.shortcode_parser.parse(string).replace(self.Config.syntax.n_temp," ")
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 219, in parse
    return stack.pop().render(context)
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 58, in render
    return ''.join(child.render(context) for child in self.children)
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 58, in <genexpr>
    return ''.join(child.render(context) for child in self.children)
  File "/home/aniket/stable-diffusion-webui/extensions/unprompted/lib/shortcodes.py", line 121, in render
    raise ShortcodeRenderingError(msg) from ex
lib.shortcodes.ShortcodeRenderingError: An exception was raised while rendering the 'file' shortcode in line 1.

**Comment by aniketgore** [comment]
Also negative prompt is still not working and I've updated to version 0.9

No module 'xformers'. Proceeding without it.
Dreambooth API layer loaded
(Unprompted v0.9.0 by Therefore Games)
(SETUP) Initializing Unprompted object...
(SETUP) Loading configuration files...
(SETUP) Debug mode is False

**Comment by aniketgore** [comment]
![Snapshot_2022-11-30_13-19-32](https://user-images.githubusercontent.com/22811139/204737976-7c38b018-7887-4042-8427-fff591749a64.png)

**Comment by ThereforeGames** [comment]
Hi @aniketgore,

The random.choice function can produce `IndexError: list index out of range` when the list of choices is empty. Are you sure b/places/* is the correct path to your files?

A few other diagnostic questions if you don't mind:

- Which other extensions do you have installed?
- Are you on the latest version of the WebUI?
- Are you using config_user.json, and if so, what are your settings there?

Thank you!

**Comment by alexanderdutton** [comment]
I'm absolutely trying to use the [repeat] to produce results which are usually 0-3 items. As in, compile a random assortment of adjectives, 0-n.

None, for my purposes, should be an appropriate amount to return, without error.

> [repeat _times="<random 2>"] 

I'd prefer it to simply return nothing if that's the allowable range I've offered -- does that not track?

I could certainly nest it within a [choose] and qualify the difference of the random options (1-2|.33), but the other method feels more streamlined to my mind, at least in this case. Is there a config option for ignoring empty sets?

Thanks!

**Comment by ThereforeGames** [comment]
Hi @alexanderdutton,

That certainly sounds like a valid use case - are you saying that `[repeat 0]` is returning an error when used in conjunction with `[file]`? As far as I can tell, `[repeat 0]` does not throw an error on its own (although it can lead to weird truncation as you pointed out in another issue - I'm still looking into that.)

Just want to make sure I'm on the same page. In the meantime, I will look into updating `[file]` so that it can accept non-existent filepaths, maybe with a config option.

**Comment by ThereforeGames** [comment]
As of v2.0.1, the `[file]` shortcode will no longer halt Unprompted if the file does not exist. Instead, you will get a soft error message in the console. I may add an argument to `[file]` or a config option to suppress the error entirely - thoughts?

**Comment by alexanderdutton** [comment]
Sounds good to me. I'll give it a try.

Thanks for your work! I'm very much appreciating the versatility.
