### ISSUE TITLE
No module named 'lib.simpleeval'

### ISSUE THREAD

**Issue by Nitrobacters** [ThereforeGames/unprompted#24]
Hey, with the last unprompted update I have this error : 
```
Traceback (most recent call last):
  File "D:\Téléchargement\Super Stable Diffusion 2.0\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\Téléchargement\Super Stable Diffusion 2.0\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\Téléchargement\Super Stable Diffusion 2.0\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 19, in <module>
    Unprompted = Unprompted(base_dir)
  File "D:\Téléchargement\Super Stable Diffusion 2.0\stable-diffusion-webui\extensions\unprompted\lib\shared.py", line 42, in __init__
    spec.loader.exec_module(self.shortcode_modules[shortcode_name])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Téléchargement\Super Stable Diffusion 2.0\stable-diffusion-webui\extensions\unprompted/shortcodes\basic\eval.py", line 1, in <module>
    from lib.simpleeval import simple_eval
ModuleNotFoundError: No module named 'lib.simpleeval'
```
I use last Automatic111, and have the extension below : 

a1111-sd-webui-tagcomplete
deforum-for-automatic1111-webui
depthmap2mask
sd-dynamic-prompts
sd_dreambooth_extension
stable-diffusion-webui-artists-to-study
stable-diffusion-webui-inspiration
unprompted

I already tried to pip install simple eval.

Thanks!

**Comment by ThereforeGames** [comment]
Hi @Nitrobacters, sorry about that! It looks like the .gitignore file excluded the new simpleeval dependency. Should be fixed now.

Let me know if the latest version works for you.

**Comment by Nitrobacters** [comment]
No problem, always something like that ^^
All work for me thanks you !
