### ISSUE TITLE
txt2img2img non functional.

### ISSUE THREAD

**Issue by redactedaccount** [ThereforeGames/unprompted#249]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [X] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

Using txt2img2img uh.. doesn't work.  Will generate the first image, then try to generate the next one, but produces a weird mask file, and some image with the mask applied but that's it. Traceback shows AttributeErrors

Running into a lot of issues with shortcodes.  Some I'm still trying to figure out if they're my fault or not, but this one I've narrowed down pretty well I think.  

### Prompt

Unprompted Enabled: True, Unprompted Prompt: [call 'common/functions/txt2img2img' subject_a='red apple' subject_b='cartoon character' template_name='txt2img2img'], Unprompted Seed: 3708169498, Version: v1.9.0

### Log output

```shell
100%|██████████| 20/20 [00:03<00:00,  5.22it/s]
2024-05-12 21:04:06,546  (ERROR)    [Unprompted.after] Exception while trying to bypass an extension: controlnet
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/extensions/_unprompted/shortcodes/basic/after.py", line 69, in after
    cn_module = helpers.import_file(f"{self.Unprompted.Config.stable_diffusion.controlnet.extension}.{cn_lib}.external_code", f"{cn_path}/{cn_lib}/external_code.py")
  File "/workspace/stable-diffusion-webui/extensions/_unprompted/lib_unprompted/helpers.py", line 141, in import_file
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
    from .args import ControlNetUnit
ModuleNotFoundError: No module named 'sd-webui-controlnet'
2024-05-12 21:04:06,547  (INFO)     [Unprompted.after] Processing After content for batch 0, block 0...
2024-05-12 21:04:09,273  (ERROR)    [Unprompted.img2img] Exception while running the img2img task
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/extensions/_unprompted/shortcodes/stable_diffusion/img2img.py", line 89, in run_atomic
    img2img_result = img2img_func(
  File "/workspace/stable-diffusion-webui/extensions/_unprompted/shortcodes/stable_diffusion/img2img.py", line 234, in img2img_patched
    p.scripts = self.Unprompted.shortcode_user_vars["scripts"].copy()  # modules.scripts.scripts_img2img
AttributeError: 'ScriptRunner' object has no attribute 'copy'
2024-05-12 21:04:09,273  (ERROR)    [Unprompted.img2img] The returned object does not appear to contain an image: []
Total progress: 100%|██████████| 20/20 [00:06<00:00,  3.05it/s]
Total progress: 100%|██████████| 20/20 [00:06<00:00,  5.38it/s]
```

### Unprompted version

There is no 'About' tab in the WebUI, update this too.  Here's the version via github commit: 697a6f61

### WebUI version

v1.9.0

### Other comments

Extra:
The thing I'm really trying to figure out is how to hold variables between generations. If you had a good answer for that that'd be helpful. Say, if I randomly select a number with [choose] how do I keep that number for the next generation?

Would like to basically make conditional 'choose your own adventures' based on previously generated variables. Tried this with Dynamic Prompts, which is also half-busted. Tried using the A1111 API, but that's busted, so now I'm here.

**Comment by ThereforeGames** [comment]
Hi @redactedaccount,

Thank you for reaching out - I was able to reproduce the problem with `txt2img2img` and I think I managed to resolve it in v11.0.1.

Feel free to give the new version a try and let me know if it still gives you any trouble. Thanks!
