### ISSUE TITLE
txt2mask error

### ISSUE THREAD

**Issue by Nix-id** [ThereforeGames/unprompted#259]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [X] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

just try to test it after install in extension tab.

![image](https://github.com/user-attachments/assets/1ff326c9-c510-4185-adc2-bba89fd54843)

### Prompt

[txt2mask show]face[/txt2mask]

### Log output

```shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
Installing requirements for Unprompted - natural language processing: pattern@git+https://github.com/NicolasBizzozzero/pattern
Unprompted - Copying ControlNet dependencies to venv...
Copy error: [WinError 183] Cannot create a file when that file already exists: 'D:\\sd.webui\\webui\\extensions\\_unprompted/../../venv/Lib/site-packages/cldm'
Launching Web UI with arguments:
D:\sd.webui\system\python\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
2024-11-06 21:24:43,115  (INFO)     [Unprompted] Loading Unprompted v11.2.0 by Therefore Games
2024-11-06 21:24:43,115  (INFO)     [Unprompted] Initializing Unprompted shortcode parser...
2024-11-06 21:24:43,143  (INFO)     [Unprompted] Finished loading in 0.0279996395111084 seconds.
D:\sd.webui\system\python\lib\site-packages\timm\models\registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
Loading weights [c6bbc15e32] from D:\sd.webui\webui\models\Stable-diffusion\sd-v1-5-inpainting.ckpt
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 16.9s (prepare environment: 9.3s, import torch: 3.2s, import gradio: 0.7s, setup paths: 0.7s, initialize shared: 0.3s, other imports: 0.4s, load scripts: 1.1s, create ui: 0.8s, gradio launch: 0.3s).
Creating model from config: D:\sd.webui\webui\configs\v1-inpainting-inference.yaml
D:\sd.webui\system\python\lib\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Applying attention optimization: Doggettx... done.
Model loaded in 5.2s (load weights from disk: 3.6s, create model: 0.3s, apply weights to model: 1.0s, calculate empty prompt: 0.2s).
2024-11-06 21:25:33,396  (ERROR)    [Unprompted] Could not parse contents.
Traceback (most recent call last):
  File "D:\sd.webui\webui\extensions\_unprompted\lib_unprompted\shortcodes.py", line 164, in render
    return str(self.handler(self.token.keyword, self.pargs, self.kwargs, context, content))
  File "D:\sd.webui\webui\extensions\_unprompted\lib_unprompted\shared.py", line 103, in handler
    return (self.shortcode_objects[f"{keyword}"].run_block(pargs, kwargs, context, content))
  File "D:\sd.webui\webui\extensions\_unprompted/shortcodes\stable_diffusion\txt2mask.py", line 24, in run_block
    self.Unprompted.shortcode_install_requirements("", ["segment_anything"])
  File "D:\sd.webui\webui\extensions\_unprompted\lib_unprompted\shared.py", line 773, in shortcode_install_requirements
    if self.Config.skip_requirements:
AttributeError: 'types.SimpleNamespace' object has no attribute 'skip_requirements'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\sd.webui\webui\extensions\_unprompted\lib_unprompted\shared.py", line 252, in process_string
    string = self.shortcode_parser.parse(self.sanitize_pre(string, self.Config.syntax.sanitize_before), context)
  File "D:\sd.webui\webui\extensions\_unprompted\lib_unprompted\shortcodes.py", line 286, in parse
    return stack.pop().render(context).replace(self.esc_start, "")
  File "D:\sd.webui\webui\extensions\_unprompted\lib_unprompted\shortcodes.py", line 60, in render
    return ''.join(child.render(context) for child in self.children)
  File "D:\sd.webui\webui\extensions\_unprompted\lib_unprompted\shortcodes.py", line 60, in <genexpr>
    return ''.join(child.render(context) for child in self.children)
  File "D:\sd.webui\webui\extensions\_unprompted\lib_unprompted\shortcodes.py", line 168, in render
    raise ShortcodeRenderingError(msg) from ex
lib_unprompted.shortcodes.ShortcodeRenderingError: An exception was raised while rendering the 'txt2mask' shortcode in line 1.
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00, 10.62it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00, 11.40it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00, 12.49it/s]
```

### Unprompted version

12942486

### WebUI version

v1.10.1

**Comment by tooonuch** [comment]
hey @Nix-id
Also noticed this issue, here's a quick and dirty fix (but not a real solution for the long-term): 
1. in the installed extension files go to lib_unprompted/shared.py
2. comment out or delete lines 773-775, as per screenshot
![image](https://github.com/user-attachments/assets/614cd59c-7f64-420d-96a2-b5d252d36fb2)
3. restart everything and now the code should work
