### ISSUE TITLE
Unprompt error with new unprompt_seed function TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by raymondgp** [ThereforeGames/unprompted#57]
While trying the new v7 (coming from 5.2) I find an error stopping Unprompted.

Scenario below is with Unpromted seed = -1 

The code in question was generated by the wizard:

[txt2mask mode="add" show precision=100.0 smoothing=20.0 neg_precision=100.0 neg_smoothing=20.0]face[/txt2mask]

Call fails either by letting the wizard "Auto-Include" or by setting manually in the prompt

----------------Error Trace----------------------------
Error running process: D:\AI\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "D:\AI\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 342, in process
    random.seed(unprompted_seed)
  File "C:\Users\Ray_3d\AppData\Local\Programs\Python\Python310\lib\random.py", line 167, in seed
    super().seed(a)
TypeError: unhashable type: 'list'

**Comment by raymondgp** [comment]
Update: 

Problem was a conflict with the stable-diffusion-webui-randomize  extension. Found out by reading other issues.
Not sure if to leave ticket open here so developers can identify the conflict, or if close it.

**Comment by ThereforeGames** [comment]
Thanks for the update, @raymondgp - I'll leave this issue open until I have a chance to try the randomize extension myself and see what's causing the conflict.
