### ISSUE TITLE
NLTK resources aren't downloaded when using the new -nyms features

### ISSUE THREAD

**Issue by throttlekitty** [ThereforeGames/unprompted#66]
Using the simple example of [hypernyms]food[/hypernyms] gives the following error. From the announcement, it sounds like the script should download this for me, yeah?
I've tried restarting webui, and I'm on the most recent commits for webui and Unprompted.

```
Error running process: C:\stable-diffusion\a1-sd-webui\extensions\unprompted\scripts\unprompted.py
Traceback (most recent call last):
  File "C:\stable-diffusion\a1-sd-webui\venv\lib\site-packages\nltk\corpus\util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "C:\stable-diffusion\a1-sd-webui\venv\lib\site-packages\nltk\data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
```

**Comment by ThereforeGames** [comment]
Hi @throttlekitty ,

I added a download check for the wordnet package in Unprompted v7.4.0. Let me know if the issue persists!

**Comment by throttlekitty** [comment]
Seems to work, but each new prompt also places this in the console. Batch count or batch image will give these lines per each.

```
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\tk\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
```
