### ISSUE TITLE
ModuleNotFoundError: No module named 'sentence_transformers'

### ISSUE THREAD

**Issue by matrix4767** [ThereforeGames/unprompted#67]
Wanted to try the img2pez feature, got this:

Error running process: G:\stable-webui\extensions\unprompted\scripts\unprompted.py
Traceback (most recent call last):
  File "G:\stable-webui\extensions\unprompted\lib_unprompted\shortcodes.py", line 117, in render
    return str(self.handler(self.token.keyword, self.pargs, self.kwargs, context))
  File "G:\stable-webui\extensions\unprompted\lib_unprompted\shared.py", line 61, in handler
    return(self.shortcode_objects[f"{keyword}"].run_atomic(pargs, kwargs, context))
  File "G:\stable-webui\extensions\unprompted/shortcodes\stable_diffusion\img2pez.py", line 8, in run_atomic
    import lib_unprompted.hard_prompts_made_easy as pez
  File "G:\stable-webui\extensions\unprompted\lib_unprompted\hard_prompts_made_easy.py", line 15, in <module>
    from sentence_transformers.util import (semantic_search,
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\stable-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "G:\stable-webui\extensions\unprompted\scripts\unprompted.py", line 378, in process
    Unprompted.shortcode_user_vars["prompt"] = Unprompted.process_string(apply_prompt_template(original_prompt,Unprompted.Config.templates.default))
  File "G:\stable-webui\extensions\unprompted\lib_unprompted\shared.py", line 84, in process_string
    string = self.shortcode_parser.parse(string,context)
  File "G:\stable-webui\extensions\unprompted\lib_unprompted\shortcodes.py", line 219, in parse
    return stack.pop().render(context)
  File "G:\stable-webui\extensions\unprompted\lib_unprompted\shortcodes.py", line 58, in render
    return ''.join(child.render(context) for child in self.children)
  File "G:\stable-webui\extensions\unprompted\lib_unprompted\shortcodes.py", line 58, in <genexpr>
    return ''.join(child.render(context) for child in self.children)
  File "G:\stable-webui\extensions\unprompted\lib_unprompted\shortcodes.py", line 121, in render
    raise ShortcodeRenderingError(msg) from ex
lib_unprompted.shortcodes.ShortcodeRenderingError: An exception was raised while rendering the 'img2pez' shortcode in line 1.

**Comment by matrix4767** [comment]
Nevermind, I just had to restart the webui entirely besides just enabling this extension. Works now.
