### ISSUE TITLE
Conflict with depthmap script

### ISSUE THREAD

**Issue by gsgoldma** [ThereforeGames/unprompted#73]
A different conflict with depthmap than before. Only get this error with depthmap-script extension when unprompted is also in the extensions folder: 
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 40, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "D:\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "D:\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "D:\stable-diffusion-webui\extensions/stable-diffusion-webui-depthmap-script/scripts\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

**Comment by mangocan** [comment]
I had the exact same thing happen to me.
