### ISSUE TITLE
"TypeError: Scripts.process() missing 2 required positional arguments: 'is_enabled' and 'unprompted_seed'"

### ISSUE THREAD

**Issue by hyacinthgirl16** [ThereforeGames/unprompted#76]
I just started using Unprompted a couple of days ago with automatic1111 webui. It suddenly stopped working for me and giving me the error in the title. 

I'm very new to this and don't know much about code! I am happy to provide any details I can but don't know what would be useful.

**Comment by hyacinthgirl16** [comment]
Looking at the errors, I keep getting lots of different ones, all on different lines. I tried deleting the extension and reinstalling, but it's still happening: 

This is on startup: 
Error calling: C:\stable-diffusion-webui-master\extensions\unprompted\scripts\unprompted.py/ui
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui-master\extensions\unprompted\scripts\unprompted.py", line 269, in ui
    first_line = file.readline()

This is when I try to run a prompt (any prompt, even if not unprompted format): 

Error running process: C:\stable-diffusion-webui-master\extensions\unprompted\scripts\unprompted.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
TypeError: Scripts.process() missing 2 required positional arguments: 'is_enabled' and 'unprompted_seed'

And then after it generates it shows this: 
Error running postprocess: C:\stable-diffusion-webui-master\extensions\unprompted\scripts\unprompted.py0:00,  2.90it/s]
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 404, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Scripts.postprocess() missing 2 required positional arguments: 'is_enabled' and 'unprompted_seed'

The unprompted extension is there, the box is checked and seed is at -1, but the checkbox is grayed out and I can't adjust seed. 

Hope this isn't too much information, I was just loving this and then it broke!

**Comment by hyacinthgirl16** [comment]
Current startup error: 

Loading Unprompted v7.5.9 by Therefore Games
(SETUP) Initializing Unprompted object...
(SETUP) Loading configuration files...
(SETUP) Debug mode is False
Loading weights [d8691b4d16] from C:\stable-diffusion-webui-master\models\Stable-diffusion\deliberate_v11.safetensors
Creating model from config: C:\stable-diffusion-webui-master\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(1): Style-Princess
Textual inversion embeddings skipped(1): SCG768-Euphoria
Model loaded in 6.3s (load weights from disk: 0.3s, create model: 0.5s, apply weights to model: 2.0s, apply half(): 0.9s, move model to device: 0.9s, load textual inversion embeddings: 1.7s).
Error calling: C:\stable-diffusion-webui-master\extensions\unprompted\scripts\unprompted.py/ui
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui-master\extensions\unprompted\scripts\unprompted.py", line 269, in ui
    first_line = file.readline()
  File "C:\Users\hyaci\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 953: character maps to <undefined>

**Comment by ThereforeGames** [comment]
Hi @hyacinthgirl16,

This error appears to be related to a file in your `unprompted/templates` directory - I would suggest temporarily moving your templates to another location and see if it resolves the issue. If it does, you can then move the files back one-by-one until you find the culprit.

Feel free to attach the problematic template here so I can diagnose the problem further. Thanks!

**Comment by ThereforeGames** [comment]
Closing due to lack of activity, feel free to let me know if the issue persists. Recent versions of Unprompted do a better job of loading templates without crashing, so I'm guessing it might be resolved.
