### ISSUE TITLE
txt2mark does not work

### ISSUE THREAD

**Issue by ronybarbosa** [ThereforeGames/unprompted#80]
Hi there, when trying to run txt2mask shortcode I keep having the following error (I am trying to run the example):
`Traceback (most recent call last):
  File "/Users/ronybarbosatomaz/nextroll/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/Users/ronybarbosatomaz/nextroll/stable-diffusion/stable-diffusion-webui/extensions/unprompted/scripts/unprompted.py", line 397, in process
    Unprompted.shortcode_user_vars["prompt"] = Unprompted.process_string(apply_prompt_template(original_prompt,Unprompted.Config.templates.default))
  File "/Users/ronybarbosatomaz/nextroll/stable-diffusion/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shared.py", line 84, in process_string
    string = self.shortcode_parser.parse(string,context)
  File "/Users/ronybarbosatomaz/nextroll/stable-diffusion/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shortcodes.py", line 219, in parse
    return stack.pop().render(context)
  File "/Users/ronybarbosatomaz/nextroll/stable-diffusion/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shortcodes.py", line 58, in render
    return ''.join(child.render(context) for child in self.children)
  File "/Users/ronybarbosatomaz/nextroll/stable-diffusion/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shortcodes.py", line 58, in <genexpr>
    return ''.join(child.render(context) for child in self.children)
  File "/Users/ronybarbosatomaz/nextroll/stable-diffusion/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shortcodes.py", line 137, in render
    raise ShortcodeRenderingError(msg) from ex
lib_unprompted.shortcodes.ShortcodeRenderingError: An exception was raised while rendering the 'txt2mask' shortcode in line 1.`

Any ideas about what may be wrong?

**Comment by ThereforeGames** [comment]
Hi @ronybarbosa,

Apologies for overlooking this issue.

If you are still having trouble with `[txt2mask]`, please include the following diagnostic information for me:

- What is your prompt?
- Is your WebUI up-to-date?
- What other extensions are you using?

Thank you.

**Comment by ThereforeGames** [comment]
Closed as stale.
