### ISSUE TITLE
zoom_enhance: "error running postprocess" (on Mac M1)

### ISSUE THREAD

**Issue by BigZampano** [ThereforeGames/unprompted#89]
Hi there...!

I'm getting this error on Mac M1, is there anything I can do to make it run..? Seems to be related to CUDA...

-----------------------------

Error running postprocess: /Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/scripts/unprompted.py
Traceback (most recent call last):
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shortcodes.py", line 117, in render
    return str(self.handler(self.token.keyword, self.pargs, self.kwargs, context))
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shared.py", line 61, in handler
    return(self.shortcode_objects[f"{keyword}"].run_atomic(pargs, kwargs, context))
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/shortcodes/stable_diffusion/zoom_enhance.py", line 74, in run_atomic
    mask_image = self.Unprompted.shortcode_objects["txt2mask"].run_block(set_pargs,set_kwargs,None,target_mask)
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/shortcodes/stable_diffusion/txt2mask.py", line 211, in run_block
    self.image_mask = get_mask().resize((self.init_image.width,self.init_image.height))
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/shortcodes/stable_diffusion/txt2mask.py", line 115, in get_mask
    model.load_state_dict(torch.load(d64_file), strict=False);
  File "/Volumes/AI-Models/stable-diffusion-webui/modules/safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "/Volumes/AI-Models/stable-diffusion-webui/modules/safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/Volumes/AI-Models/stable-diffusion-webui/venv-torch-nightly/lib/python3.10/site-packages/torch/serialization.py", line 810, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Volumes/AI-Models/stable-diffusion-webui/venv-torch-nightly/lib/python3.10/site-packages/torch/serialization.py", line 1173, in _load
    result = unpickler.load()
  File "/Volumes/AI-Models/stable-diffusion-webui/venv-torch-nightly/lib/python3.10/site-packages/torch/serialization.py", line 1143, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/Volumes/AI-Models/stable-diffusion-webui/venv-torch-nightly/lib/python3.10/site-packages/torch/serialization.py", line 1117, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/Volumes/AI-Models/stable-diffusion-webui/venv-torch-nightly/lib/python3.10/site-packages/torch/serialization.py", line 218, in default_restore_location
    result = fn(storage, location)
  File "/Volumes/AI-Models/stable-diffusion-webui/venv-torch-nightly/lib/python3.10/site-packages/torch/serialization.py", line 183, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Volumes/AI-Models/stable-diffusion-webui/venv-torch-nightly/lib/python3.10/site-packages/torch/serialization.py", line 167, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/AI-Models/stable-diffusion-webui/modules/scripts.py", line 436, in postprocess
    script.postprocess(p, processed, *script_args)
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/scripts/unprompted.py", line 455, in postprocess
    Unprompted.shortcode_objects[i].after(p,processed)
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/shortcodes/basic/after.py", line 32, in after
    self.Unprompted.process_string(self.Unprompted.parse_alt_tags(content,"after"))
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shared.py", line 156, in parse_alt_tags
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shortcodes.py", line 219, in parse
    return stack.pop().render(context)
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shortcodes.py", line 58, in render
    return ''.join(child.render(context) for child in self.children)
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shortcodes.py", line 58, in <genexpr>
    return ''.join(child.render(context) for child in self.children)
  File "/Volumes/AI-Models/stable-diffusion-webui/extensions/unprompted/lib_unprompted/shortcodes.py", line 121, in render
    raise ShortcodeRenderingError(msg) from ex
lib_unprompted.shortcodes.ShortcodeRenderingError: An exception was raised while rendering the 'zoom_enhance' shortcode in line 1.

-----------------------------

**Comment by jwooldridge234** [comment]
Yeah I'm having this same issue.

**Comment by ThereforeGames** [comment]
Hi,

I have implemented a possible fix for this in v7.8.0. Please try updating the extension and let me know if the issue persists. Thank you!

**Comment by marvin-dent** [comment]
This helps, I can see a new progress bar after the main image is generated and webui shows several iterations of enhanced face being generated. However, only the original un-enhanced image is saved in the txt2img folder. I am on Macbook Pro M1, the prompts I am using is "a photo of walter white, full body view,[after]{zoom_enhance}[/after]"

EDIT: This is an awesome idea by the way! Thank you!

**Comment by ThereforeGames** [comment]
Thanks Marvin! Have you tried checking the "Use Workaround" box in the GUI? Alternatively, you can add it to your prompt like so:

```
[after]{zoom_enhance use_workaround}[/after]
```

This has fixed the problem for some other users.

**Comment by BigZampano** [comment]
It works now, thanks a lot for your fast response..! 
But although I have not checked "_Include original image in output window_" it does save both images, but that's not a problem...

**Comment by ThereforeGames** [comment]
> But although I have not checked "Include original image in output window" it does save both images, but that's not a problem...

Thanks, I'll look into this. Glad to hear the main issue is resolved :)
