### ISSUE TITLE
errors using zoom enhance

### ISSUE THREAD

**Issue by gruevy** [ThereforeGames/unprompted#91]
I installed this extension and did exactly one thing with it: run a prompt with [after]{zoom_enhance}[/after] at the end. I found two things. First, there's an error at start up that may or may not be related to other extensions, and then there's the tons of errors when generating. The face replacement doesn't seem to work at all and the errors don't occur if i remove the zoom enhance thing. Any suggestions?

When reloading UI/starting up:

Error loading script: main.py
Traceback (most recent call last):
  File "D:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable diffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable diffusion\stable-diffusion-webui\extensions\openpose-editor\scripts\main.py", line 77
    if (hasattr(opts, 'control_net_max_models_num'):
	
	
When generating an image with [after]{zoom_enhance}[/after] at the end:

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:13<00:00,  2.20it/s]
Error running process: D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py]
Traceback (most recent call last):
  File "D:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 682, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 477, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 488, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None

Error running process: D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-cutoff\scripts\cutoff.py
Traceback (most recent call last):
  File "D:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 8 required positional arguments: 'enabled', 'targets_', 'weight', 'disable_neg', 'strong', 'padding', 'intp', and 'debug'

Error running process: D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-multiple-hypernetworks\scripts\multiple_hypernetworks.py
Traceback (most recent call last):
  File "D:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
TypeError: MultipleHypernetworks.process() missing 2 required positional arguments: 'hypernetworks' and 'hypernetworks_strength'

Error running process: D:\stable diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py
Traceback (most recent call last):
  File "D:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
TypeError: ComposableLoraScript.process() missing 3 required positional arguments: 'enabled', 'opt_uc_text_model_encoder', and 'opt_uc_diffusion_model'

Error running process: D:\stable diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py
Traceback (most recent call last):
  File "D:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 5 required positional arguments: 'enabled', 'raw_divisions', 'raw_positions', 'raw_weights', and 'raw_end_at_step'

Error running process_batch: D:\stable diffusion\stable-diffusion-webui\extensions\sd-clip_skip\scripts\clip_skip.py
Traceback (most recent call last):
  File "D:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 427, in process_batch
    script.process_batch(p, *script_args, **kwargs)
TypeError: Script.process_batch() missing 2 required positional arguments: 'clipSkip_scale' and 'ensd_scale'

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.97it/s]
Error running postprocess_batch: D:\stable diffusion\stable-diffusion-webui\extensions\sd-clip_skip\scripts\clip_skip.py
Traceback (most recent call last):
  File "D:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 445, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: Script.postprocess_batch() missing 2 required positional arguments: 'clipSkip_scale' and 'ensd_scale'

Total progress: 31it [00:17,  1.81it/s]
Total progress: 31it [00:17,  1.48s/it]

**Comment by RocketMobster** [comment]
I get the same errors.
