### ISSUE TITLE
[ERROR] During install

### ISSUE THREAD

**Issue by enzyme69** [ThereforeGames/unprompted#95]
I am getting this error, seems failing when installing extension:
```
Error code: 1
stdout: Installing requirements for Unprompted
Installing requirements for Unprompted

stderr: Traceback (most recent call last):
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions/unprompted/install.py", line 6, in <module>
    launch.run_pip("install pattern@git+https://github.com/NicolasBizzozzero/pattern","requirements for Unprompted")
  File "/Users/jimmygunawan/stable-diffusion-webui/launch.py", line 145, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/Users/jimmygunawan/stable-diffusion-webui/launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Unprompted.
Command: "/Users/jimmygunawan/stable-diffusion-webui/venv/bin/python3.10" -m pip install pattern@git+https://github.com/NicolasBizzozzero/pattern --prefer-binary
Error code: 1
stdout: Collecting pattern@ git+https://github.com/NicolasBizzozzero/pattern
  Cloning https://github.com/NicolasBizzozzero/pattern to /private/var/folders/dd/6tfdfc6x5pz37mrm2msqyc9r0000gn/T/pip-install-_glbg8_2/pattern_764531dca3a24a22b1a25bb088ea4dff
  Resolved https://github.com/NicolasBizzozzero/pattern to commit 66ab34453a3443c06a4ebda092c8d1947c83b17a
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: future in ./venv/lib/python3.10/site-packages (from pattern@ git+https://github.com/NicolasBizzozzero/pattern) (0.18.3)
Collecting backports.csv
  Downloading backports.csv-1.0.7-py2.py3-none-any.whl (12 kB)
Collecting mysqlclient
  Downloading mysqlclient-2.1.1.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.1/88.1 kB 5.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/NicolasBizzozzero/pattern /private/var/folders/dd/6tfdfc6x5pz37mrm2msqyc9r0000gn/T/pip-install-_glbg8_2/pattern_764531dca3a24a22b1a25bb088ea4dff
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /bin/sh: mysql_config: command not found
      /bin/sh: mariadb_config: command not found
      /bin/sh: mysql_config: command not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/dd/6tfdfc6x5pz37mrm2msqyc9r0000gn/T/pip-install-_glbg8_2/mysqlclient_fd67ea8fa7c14b699f15335865331cec/setup.py", line 15, in <module>
          metadata, options = get_config()
        File "/private/var/folders/dd/6tfdfc6x5pz37mrm2msqyc9r0000gn/T/pip-install-_glbg8_2/mysqlclient_fd67ea8fa7c14b699f15335865331cec/setup_posix.py", line 70, in get_config
          libs = mysql_config("libs")
        File "/private/var/folders/dd/6tfdfc6x5pz37mrm2msqyc9r0000gn/T/pip-install-_glbg8_2/mysqlclient_fd67ea8fa7c14b699f15335865331cec/setup_posix.py", line 31, in mysql_config
          raise OSError("{} not found".format(_mysql_config_path))
      OSError: mysql_config not found
      mysql_config --version
      mariadb_config --version
      mysql_config --libs
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by 0xLLLLH** [comment]
I met the same issue and fixed it by running:
```
brew install mysql-client
echo 'export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"' >> ~/.zshrc
```

**Comment by Soulreaver90** [comment]
I got the same error, first time running it and tried on a clean instance of auto1111. I am on Ubuntu 22.04

**Comment by ThereforeGames** [comment]
Hi @enzyme69 and @Soulreaver90,

I have since added a few sanity checks to `install.py` that should allow you to proceed even if some of the dependencies couldn't be installed.

This particular error is related to the patterns library that powers a few of the natural language processing shortcodes such as `[autocorrect]`. I may eventually replace the library with something that has Linux support, but that's another discussion.
